### PR TITLE
Export support for vimtyping

### PR DESCRIPTION
**Pull request by hernot**
OK finally the export works outside floats if linenumbering is off or numberlocation is default or left. Inside floats all lines are still squashed into one line as if float class or float content class makes browsers ignore css settings for vimtyping and verbatimline. But no idea. Requires further check.
Linenumbering is broken in general.
if numberlocation set to right than each line is put into its own vimtyping div. And inside floats first number is before vimtyping block and rest is after. Not sure what the reason is needs further checks.

Naming of vimtiypings not yet checked if names are all uppercase.

My branch copy was not rebased to latests on upstream. I just cherrypicked t-filter.tex and t-vim.tex and corresponding test from base/export-2 and checked them out into my copy to make insync.

### CODE REVIEW

**Comment by adityam** [comment]
Thanks. I'll take a look. 

Note that there is no point in added lua code to `.mkii` file. MkII uses  pdftex as the engine, so the lua code will not work.

**Comment by hernot** [comment]
Ok what i have found related to floats is that inside floats the whitespace inbetween `<verbatimline>` tags  and `<div class=verbatimline>` tags is still removed while without floats it is preserved in output. By manually adding whitespace to html and for better readability placing each `<verbatimline>` on its separate source line formatting of `<vimtyping>` content suddenly appears as expected. And comparing  tests/vim/37*.tex to tests/vim/38*.tex which just differ in that the latter is enclosing within floats the only true difference is exactly this kind of whithespace.

That could be also the reason for line numbering with numberlocation=left or default setting that first linenumber is placed before `<vimtyping>` tag and the rest following it. 

Have no idea how to get ridd of splitting into several `<vimtyping>` sections for numberlocation=right.

**Comment by hernot** [comment]
> Note that there is no point in added lua code to `.mkii` file. MkII uses pdftex as the engine, so the lua code will not work.

Oh sorry i missed that. Sure. I wanted anyway to mention that i have no mkii installatoin here and thus have no idea whether support for export makes any sense. Please remove form mkii files anything export related making no sense to mkii unless you haven't done anyway already.

**Comment by hernot** [comment]
As i went through open issues just for sake of completeness and to nothing miss i think this pullrequest or the final release based upon it would close #3 #31 and rendered pullrequest #34 obsolete which i already closed.

**Comment by adityam** [comment]
Thanks for cleaning up the old issues!

I have merged the changes into a new branch `export-3`. I still need to think about the best way to do this. 

Firstly, the bug with numberlocation=right should be fixed in the new release. We'll look into numbering with floats next.

1. The current code uses `\doifmode{*export}{...}`. This means that `\setupbackend[export=yes]` must happen before loading the `vim` module. It should be possible to do this by adding code to `\everyexport` tokens.

2. I am thinking of creating a high-level interface for including css as follows.
```
\setupvimtyping[cssfile=default|auto|name]
```
where `default` includes pre-written CSS files which are included (we need to create these); `auto` means auto-generated CSS files based on your code, and any other option includes the file specified by that name. 

3. I don't think that parsing of `command` key is a good idea. There is so many different ways this could be configured, that simply checking for a few pre-specified names will not work.

**Comment by hernot** [comment]
> Firstly, the bug with numberlocation=right should be fixed in the new release. We'll look into numbering with floats next.
>


Oh! did I miss a ConTeXt release or is release still pending.
 The one I tested on is: ConTeXt Process Management 1.03 current version 2020.01.30 14:13


>     1. The current code uses `\doifmode{*export}{...}`. This means that `\setupbackend[export=yes]` must happen before loading the `vim` module. It should be possible to do this by adding code to `\everyexport` tokens.


There you are more experienced which is the better and proper solution. I just took what i found in the docs. If `\everyexport` is the right than it should be changed if it has the same effect that css is only included or created if export to html, xhtml and xml is active otherwise I do not see any reason for doing.  


> 
>     2. I am thinking of creating a high-level interface for including css as follows.
> 
> 
> ```
> \setupvimtyping[cssfile=default|auto|name]
> ```
> 
> where `default` includes pre-written CSS files which are included (we need to create these); `auto` means auto-generated CSS files based on your code, and any other option includes the file specified by that name.
> 


For the default (pre-written) I'd suggest to just pick a few syntaxgroups for styling with a fixed style for each to cover major syntax groups or at least most important thereof and ignore the rest which could not be present in all languages supported by vim. As a starting template the ones currently autocreated could be used. Cleaning up a few things.
Limiting the styling to subitmes of `vimtyping[detail=colorscheme]` should be kept in any case to avoid side effects when users also utilize typing environment and others.


>     1. I don't think that parsing of `command` key is a good idea. There is so many different ways this could be configured, that simply checking for a few pre-specified names will not work.

Hm I fear that CSS will be the limiting factor here not providing much options here that in worst either most commands must be ignored anyway or must be converted to some xml/html tags which decorate either the `syntaxgroup` as a whole or its content to achieve the appropriate styling. I can check what options CSS offers beyond colour and font and the ones parsed. Than a decision could be made whether to take some efforts beyond and how or skip command completely.

**Comment by adityam** [comment]
There is a new release typically every couple of days. There was one released yesterday and a new update today which fixes the export of linenumbers of the right.

**Comment by hernot** [comment]
I went through the list of possible CSS attributes which could be used as shortcut for handling content of `command` paremeter. In general to map `command` onto HTML and/or XHTML/XML using CSS there are two general possiblitlities:

A) the command implements tagging either using `\dostarttagging \dostoptagging` or `\startelement \stopelement` properly and provides its own CSS snipped.
   - The advantage is that no further action is necessary exempt ensuring that tag(s) inserted by `command` either are properly enclosed within `<syntaxgroup>` or properly decorate it. 
   - The disadvantage is that each `<div>` tag resembles an individual box with a content area, a boarder and a margin. In worst each `<div>` adds in addition to the desired decoration addtoinal space between its boundary and the inner content thereby changing layout of document unexpectedly.

B) do not rely upon implementation of command and establish a mapping between ConTeXt styling commands / styles and CSS style attributes.
  - The advantage is no dependency upon implementation and CSS styling of `<div>` tags corresponding to `command` if any and the styling of `<syntaxgroup>` tags.
  - The disadvantage is requires strategy to map between `command` and CSS attribute or attributes if to be split onto multiple. 
  - The second disadvantage is that mapping can grow quite complex task given the large number of possibilities to change all or only parts.

I have too little knowhow upon ConTeXt inner workings and design guidelines related to XML/HTML export especially to be able to judge that or even express some helpful preference. I'm not sure if it would be helpful in decision between the two options above but i have compiled a list of CSS attributes which commands could be mapped to if mapping should be an option at all. As you will see the majority of CSS attributes does not add additional options but just limits style to some substyle or subitem of a more general style eg. `boarder` defines all four sides of the border whereas `boarder-left` limits the whole just to the left line of the boarder frame.

 I have split the list into several sections. The first contains the attributes which i would consider reasonable within the context of vimtyping. The second contains attributes where i have the impression or the maybe false idea that these are handled anyway by ConTeXt implicitly or differently. It also contains those where I know that they are set by vimtyping to values which ensure proper display. 
The third section contains basically stuff where i have no idea if they would be relevant at all for vimtyping and also do not feel having enough knowledge to judge about.
And the last section contains attributes where when playing arround with CSS had the impression that they behave at least in firefox and chrome differently when displaying html output or xml/xhtml output.

Feel free to ignore the list, or edit it in case mapping could be at least for some very common style commands be an option to make output in html and xml/xhtml appear as expected from corresponding pdf output. 

[context-css-mapable-attr.md.txt](https://github.com/adityam/filter/files/4842345/context-css-mapable-attr.md.txt)
(content is in markdown eventhough ending states txt)

**Pull request merged**
